// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InsufficientStorageChartAPIError Insufficient storage
//
// swagger:model InsufficientStorageChartAPIError
type InsufficientStorageChartAPIError struct {
}

// Validate validates this insufficient storage chart API error
func (m *InsufficientStorageChartAPIError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InsufficientStorageChartAPIError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InsufficientStorageChartAPIError) UnmarshalBinary(b []byte) error {
	var res InsufficientStorageChartAPIError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
